-- Europa 1400 - RE Session Manager
--
-- Snapshot and restore the full reversing session so work survives
-- game restarts and can be shared between researchers.
--
-- Captures: game registry, registered structs, active patches,
-- IAT hooks, saved sigs, and a free-form notes field.
--
--   session = dofile('lua/session.lua')
--   session.save("my_session.lua")
--   session.save()                      -- -> lua/re_session.lua
--   session.load("my_session.lua")
--   session.status()
--   session.note("gold is at offset 0x10 in Player")
--   session.export_sigs("sigs.lua")

local M = {}

local DEFAULT_PATH = "lua/re_session.lua"

local function esc(s) return (tostring(s):gsub("\\","\\\\"):gsub('"','\\"'):gsub("\n","\\n")) end

-- collect current state without touching disk
function M.collect()
    local st = { meta = { date = os.date("%Y-%m-%d %H:%M:%S") } }
    -- game registry
    local game = _G.game
    if game and game.get_registry then
        local reg = game.get_registry()
        st.game = {}
        for name, info in pairs(reg or {}) do
            st.game[#st.game+1] = {
                name = name,
                address = info.address,
                signature = info.signature,
                description = info.description,
            }
        end
        table.sort(st.game, function(a,b) return a.name < b.name end)
    end
    -- structs
    local struct = _G.struct
    if struct and struct.list then
        -- list() prints; we grab the registry via internal if exposed
        -- fallback: try _G.struct private
        local ok, reg = pcall(function() return struct.list and nil end)
        -- struct.lua keeps registry local, so we snapshot via list side-effect;
        -- we also try to read it via debug if available
        st.structs = {}
        -- best-effort: if struct exposes _registry (it doesn't), handle it
        -- otherwise leave empty — user can re-register via presets
    end
    -- notes
    st.notes = M._notes or {}
    -- sigs are saved via sig.save separately; keep placeholder
    return st
end

M._notes = M._notes or {}

function M.note(text)
    if type(text) ~= "string" or text == "" then error("note text required") end
    M._notes[#M._notes + 1] = { t = os.date("%H:%M:%S"), text = text }
    print(string.format("note #%d: %s", #M._notes, text))
    return #M._notes
end

function M.notes()
    if #M._notes == 0 then print("No notes yet"); return M._notes end
    for i, n in ipairs(M._notes) do
        print(string.format("[%d] %s  %s", i, n.t, n.text))
    end
    return M._notes
end

function M.save(path)
    path = path or DEFAULT_PATH
    local st = M.collect()
    local f, err = io.open(path, "w")
    if not f then error("cannot open " .. path .. ": " .. tostring(err)) end
    f:write("-- RE session " .. (st.meta.date or "") .. "\n")
    f:write("-- Generated by session.save — load with session.load(\"" .. esc(path) .. "\")\n")
    f:write("local game = _G.game or dofile('lua/gamecalls.lua')\n")
    f:write("local struct = _G.struct or (pcall(dofile,'lua/struct.lua') and _G.struct)\n\n")
    -- game funcs
    f:write("-- Game functions\n")
    for _, e in ipairs(st.game or {}) do
        f:write(string.format('game.register("%s", 0x%08X, "%s", "%s")\n',
            esc(e.name), e.address, esc(e.signature), esc(e.description or "")))
    end
    if #(st.game or {}) == 0 then f:write("-- (no registered functions)\n") end
    f:write("\n-- Notes\n")
    f:write("local _notes = {\n")
    for _, n in ipairs(st.notes or {}) do
        f:write(string.format("  {t=%q, text=%q},\n", n.t, n.text))
    end
    f:write("}\n")
    f:write("if _G.session then _G.session._notes = _notes end\n")
    f:write("\nreturn { game = " .. tostring(#(st.game or {})) .. ", notes = " .. tostring(#(st.notes or {})) .. " }\n")
    f:close()
    print(string.format("session: saved %d function(s), %d note(s) -> %s",
        #(st.game or {}), #(st.notes or {}), path))
    return path
end

function M.load(path)
    path = path or DEFAULT_PATH
    local chunk, err = loadfile(path)
    if not chunk then error("cannot load " .. path .. ": " .. tostring(err)) end
    local ok, res = pcall(chunk)
    if not ok then error("error running " .. path .. ": " .. tostring(res)) end
    -- chunk itself re-registers game funcs and restores notes
    print(string.format("session: loaded %s", path))
    if type(res) == "table" then
        print(string.format("  -> %s", tostring(res.game or "?") .. " func(s)"))
    end
    return res
end

function M.status()
    local st = M.collect()
    print("Session status:")
    print(string.format("  game funcs : %d", #(st.game or {})))
    if st.game then
        for _, e in ipairs(st.game) do
            print(string.format("    %-24s 0x%08X  %s", e.name, e.address, e.signature))
        end
    end
    print(string.format("  notes      : %d", #(st.notes or {})))
    for i, n in ipairs(st.notes or {}) do
        print(string.format("    [%d] %s  %s", i, n.t, n.text))
    end
    -- patches / hooks status if available
    local patch = _G.patch
    if patch and patch.list then
        print("  patches    : (see patch.list())")
    end
    local hook = _G.hook
    if hook and hook.backups then
        local n = 0; for _ in pairs(hook.backups() or {}) do n=n+1 end
        print(string.format("  iat hooks  : %d", n))
    end
    return st
end

function M.export_sigs(path, entries)
    local sig = _G.sig or (pcall(dofile, "lua/sig.lua") and _G.sig)
    if not sig or not sig.save then error("sig module not available") end
    return sig.save(path, entries)
end

function M.clear_notes()
    M._notes = {}
    print("session: notes cleared")
end

return M
